spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour
    username: user
    password: 123456
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true